version: "3.8"

services:
  app:
    container_name: lit_app
    build: .
    stdin_open: true
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - .:/app

  postgres:
    container_name: lit_postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=""
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
